package-lock.json

START: Começando Projeto

---

package-lock.json
src/App.js
src/styles/global.css

Começando mais um projeto, commit inicial. 🚀

Grupo 7 - estrutura inicial

---

package-lock.json
src/App.js
src/context/RecipesContext.js
src/context/RecipesProvider.js
src/index.js
src/pages/Login.js

[Group 26] Login

---

package-lock.json
package.json
src/App.js
src/index.js
src/pages/Login.js

[GROUP 31] Requisitos 2, 3 e 4

[GROUP 31] Requisitos 2, 3 e 4

---

package-lock.json
package.json

[GROUP-31]Iniciando o projeto Receita APP

[GROUP-31]Iniciando o projeto Receita APP

---

package-lock.json
src/App.js
src/contexts/DrinksContext.jsx
src/contexts/DrinksProvider.jsx
src/contexts/MealsContext.jsx
src/contexts/MealsProvider.jsx
src/index.js

Implementações iniciais, providers, contexts e pastas

[Grupo 22] Req-00

---

src/apis/MealsApis.js

feita a chamada das apis de comida por filtro e searchtext.

Main group 24 api meals filter

---

src/components/fooder.jsx
src/pages/comidas.jsx

Main group 32 fooder req.19

---

README.md
src/App.js
src/context/RecipesProvider.js
src/pages/Login.js

Tentando melhorar a legibilidade do código.

[Grupo 26] Refatorando Login

---

src/components/footer.jsx
src/css/footer.css
src/pages/comidas.jsx

Footer - Requisito 20

---

src/App.js
src/components/footer.jsx
src/css/footer.css
src/pages/bebidas.jsx
src/pages/comidas.jsx

Requisito 22
Requisito 23
Requisito 24

Main group 32 footer requisitos 22 - 24

---

src/App.js
src/components/Footer.js
src/components/style/Footer.css
src/data/pathLocationNames.js
src/pages/FoodList.js

[Group 26] Menu Inferior

---

src/App.js
src/context/RecipesProvider.js
src/pages/Explore.js
src/pages/ExploreDrinks.js
src/pages/ExploreFood.js
src/services/RandomRacipeAPI.js

[Group 26] Page explore

---

src/App.js
src/components/header.jsx
src/components/searchBar.jsx
src/pages/bebidas.jsx
src/pages/comidas.jsx
src/pages/telaDePerfil.jsx

Group32 tela de usuario

---

package-lock.json
src/components/Footer.jsx
src/pages/BeverageIngredients.js
src/pages/Beverages.js
src/pages/Explore.js
src/pages/ExploreBeverages.js
src/pages/ExploreFood.js
src/pages/Food.js
src/pages/FoodByOrigin.js
src/pages/FoodIngredients.js
src/pages/Profile.js

[GROUP 31] Main group 31 - Requisitos 19 até o 24

---

src/components/Header.js
src/components/SearchBar.js
src/context/RecipesProvider.js
src/pages/foods/Recipes.js
src/services/CocktailApi.js
src/services/FoodApi.js

Header e requsiçoes

---

src/pages/Explore.jsx

Tela de explorar concluída, referente aos requisitos de 67 à 69.

[Grupo 18][Tela de explorar]

---

src/components/DoneButton.jsx
src/components/FavoriteButton.jsx
src/components/LogoutButton.jsx
src/pages/Profile.jsx

Requisitos de 82 à 87 referentes à tela de perfil.

[Grupo 18][Tela de perfil]

---

src/components/ExploreAreaButton.jsx
src/components/ExploreIngredientButton.jsx
src/components/ExploreSurpriseButton.jsx
src/pages/ExploreDrinks.jsx
src/pages/ExploreFoods.jsx

Tela de explorar bebidas e comidas concluída, referente aos requisitos de 70 à 74.

[Grupo 18][Tela de explorar bebidas e comidas]

---

src/App.css

[Grupo 18][Correção de erros]

---

src/App.js
src/components/DropDownList.jsx
src/context/Provider.jsx
src/pages/FoodArea.jsx
src/pages/NotFound.jsx

Tela de explorar por local de origem/area concluída

[Grupo 18][Tela de explorar por local de origem/area]

---

src/components/Card.jsx
src/components/MainCards.jsx
src/contexts/CocktailsProvider.jsx
src/contexts/MealsProvider.jsx
src/helpers/CocktailsAPI.js
src/helpers/api.js
src/pages/Bebidas.jsx
src/pages/Comidas.jsx

Refatorado os seguintes arquivos:
- MainCards;
- Cards;
- CocktailsProvider;
- CocktailsAPI;
Tela de comidas e bebidas já estão renderizando as 12 receitas de cada.

[Grupo 22] Req-25-26

---

src/App.js
src/context/RecipesProvider.js
src/pages/ExploreArea.js
src/pages/ExploreDrinks.js
src/pages/IngredientDrink.js
src/pages/NotFound.js
src/pages/style/ExploreArea.css
src/pages/style/ExploreDrinks.css
src/services/APIEndpoints.js
src/services/RecipesAPI.js

[Group 26] area

---

cypress/integration/footer_spec.js
cypress/integration/recipes_list_spec.js
src/App.css
src/App.test.js
src/api/fetchCategories.js
src/components/FilterBar.js
src/context/RecipesProvider.js
src/pages/Bebidas.js
src/pages/Comidas.js
src/pages/Explorar.js

Pessoal, o teste passa ao encontrar os botões e data-testId na tela de COMIDAS, porém falha ao não encontrá-los na tela de BEBIDAS. Penso que o teste executa antes da tela ser carregada, então pode ser algo relacionado a sincronismo dos eventos. Preciso de apoio. Abraço!

[Grupo 15] Requisito 27: Parcial 50% (Não encontra os botoes na tela de bebidas)

---

src/pages/Explore/Explore.js
src/pages/User/Login.js
src/pages/User/Perfil.js

[Grupo 6][Feat][Reqs-67-68-69]

---

src/components/RenderDrink.jsx
src/components/RenderDrinkIngredient.jsx
src/components/RenderMeal.jsx
src/components/RenderMealIngredient.jsx
src/context/Provider.jsx
src/pages/ExploreDrinkIngredients.jsx
src/pages/ExploreMealIngredients.jsx
src/pages/MainDrink.jsx
src/pages/MainFood.jsx

Tela de explorar por ingredientes feita! (Ocorreu um erro no requisito 16)

[Grupo 18][Tela de ingredientes]

---

src/App.js
src/components/FoodPage.jsx
src/components/SBElements.jsx

[Grupo 10] Requisito 14

---

package-lock.json
package.json
src/App.js
src/components/CardsCarousel.css
src/components/CardsCarousel.js
src/components/DetailsImage.js
src/components/EmbedVideo.js
src/components/Ingredients.js
src/components/Instructions.js
src/components/Title.js
src/pages/DetailsButton.js
src/pages/ReceitaDetalhes.css
src/pages/ReceitaDetalhes.js
src/pages/ReceitaEmProgresso.js
src/services/CheckFavorites.js
src/services/CheckInProgress.js
src/services/RecipeDetailsFetch.js
src/services/SaveWithFavorites.js

Faltam ainda os requisitos 40 e 43

G9 Tela de Detalhes

---

src/App.js
src/pages/Ingredientes.jsx

G9 receita em progresso

---

src/App.js
src/pages/DoneRecipes.js
src/pages/Profile.js
src/pages/style/DoneRecipes.css
src/services/endpoints.js
src/services/recipesAPI.js

[Group 26] done recipes

---

src/components/FavoriteButton.jsx
src/pages/Perfil.js
src/pages/RecipeInProgress.js

Main group 13 req50e51

---

src/App.js
src/pages/FavoriteRecipes.js
src/pages/style/FavoriteRecipes.css

[Group 26] favorite recipes

---

src/App.js
src/components/FoodCard.js
src/components/style/FoodCard.css
src/context/RecipesProvider.js
src/pages/DoneRecipes.js
src/pages/DrinksIngredients.js
src/pages/DrinksRecipes.js
src/pages/ExploreByArea.js
src/pages/FavoriteRecipes.js
src/pages/MealsIngredients.js
src/pages/MealsRecipes.js
src/pages/Recipes.js
src/services/endpoints.js
src/services/recipesAPI.js

Main group 26 new header

---

package-lock.json
package.json
src/App.css
src/App.js
src/components/Card.jsx
src/components/Categories.jsx
src/components/Footer.jsx
src/components/MainCards.jsx
src/components/Recommended.jsx
src/components/SearchBar.jsx
src/contexts/RecipesProvider.jsx
src/helpers/CocktailsAPI.js
src/helpers/HelperFunctions.js
src/helpers/MealsAPI.js
src/pages/Details.jsx
src/pages/Explorar.jsx
src/pages/MainPage.jsx
src/pages/Perfil.jsx

[Grupo 22] Details Spec

---

src/App.css
src/App.js
src/components/Card.jsx
src/components/Categories.jsx
src/components/Footer.jsx
src/components/MainCards.jsx
src/components/Recommended.jsx
src/components/SearchBar.jsx
src/contexts/RecipesProvider.jsx
src/helpers/CocktailsAPI.js
src/helpers/MealsAPI.js
src/pages/Details.jsx
src/pages/Explorar.jsx
src/pages/MainPage.jsx
src/pages/Perfil.jsx

Refatorei parte das API's: o componente MealsApi está próximo de fazer chamadas genéricas de api, tanto para meal como para cocktails, faltam apenas alguns detalhes.

[Grupo 22] Req 15-18 e Refatoração

---

src/App.js
src/pages/ReceitasFeitas.jsx

Main group 28 tela receitas feitas

---

src/components/Header.jsx
src/pages/DoneRecipes.jsx
src/pages/Explore.jsx
src/pages/ExploreArea.jsx
src/pages/ExploreIngredients.jsx
src/pages/ExploreMealsOrDrinks.jsx
src/pages/FavoriteRecipes.jsx
src/pages/Profile.jsx
src/services/getPageTitle.js

Add Header on the required pages and fix user email on local storage for the tests

[GRUPO 30] task: Add Header on the required pages

---

src/App.js
src/pages/ExplorarComidasPorIngredientes.jsx
src/services/outroServiceAPI.js

[Grupo 28] - Tela de Explorar por Ingredientes

---

src/components/DoneButton.jsx
src/components/ExploreAreaButton.jsx
src/components/ExploreIngredientButton.jsx
src/components/ExploreSurpriseButton.jsx
src/components/FavoriteButton.jsx
src/components/LogoutButton.jsx
src/components/RenderDrink.jsx
src/components/RenderDrinkIngredient.jsx
src/components/RenderMeal.jsx
src/components/RenderMealIngredient.jsx
src/pages/Explore.jsx
src/pages/ExploreDrinkIngredients.jsx
src/pages/ExploreDrinks.jsx
src/pages/ExploreFoods.jsx
src/pages/ExploreMealIngredients.jsx
src/pages/FoodArea.jsx
src/pages/Profile.jsx
src/styles/explore.css
src/styles/exploreArea.css
src/styles/exploreMealsIngredients.css
src/styles/header.css
src/styles/mainPage.css
src/styles/profile.css

Main group 18 css

---

src/components/DrinkPrepProgress.jsx
src/components/DrinkPreparation.jsx
src/components/FoodPrepProgress.jsx
src/components/FoodPreparation.jsx
src/components/Header.jsx
src/pages/DrinkInProgress.jsx
src/pages/FavoritesRecipes.jsx
src/pages/FoodDetails.jsx
src/pages/FoodInProgress.jsx
src/pages/Login.jsx

tela de progresso e receitas favoritas

[Group 25] [receitas favoritas]

---

src/pages/FoodByOrigin.js

Main group 31 requisitos 78 81

[Main group 31] [Requisitos 78 81]

---

src/pages/ReceitasFavoritas.js

Main group 15 reqs 60 66

---

src/pages/ReceitaDetalhes.js
src/pages/ReceitaEmProgresso.js
src/pages/RecipesFavorite.jsx

Reverts tryber/sd-010-b-project-recipes-app#748

Revert "Main group 9 adicional tela favorites"

---

src/common/pages/Login.jsx

[GRUPO 19] AJUSTE GIT

---

src/pages/Detalhes/startButton.js
src/pages/Explore/Explore.js

Requisitos 67, 68 e 69 concluídos

Main group 23 tela explorar

---

src/App.js
src/components/Card.jsx
src/components/DoneCard.jsx
src/components/MainCards.jsx
src/components/Recommended.jsx
src/components/SearchBar.jsx
src/helpers/HelperFunctions.js
src/helpers/MealsAPI.js
src/pages/DoneRecipes.jsx
src/pages/ExploreArea.jsx
src/pages/ExploreRecipes.jsx
src/pages/FavoriteRecipes.jsx

Implemented Random Recipe - Surprise Me button

[Grupo 22] Req 74

---

src/components/BodyFavoriteRecipes.jsx
src/components/BodyRecipesDone.jsx
src/components/Header.jsx
src/components/HeaderSearchBar.jsx
src/components/HeaderSearchButton.jsx
src/components/IngredientCard.jsx
src/components/RecipeCard.jsx
src/components/ShareButtonDoneRecipes.jsx
src/components/loopIngredientsAndMeasure.jsx
src/context/GlobalProvider.js
src/data/initialData.js
src/pages/DrinkDetails.jsx
src/pages/DrinkInProgress.jsx
src/pages/Drinks.jsx
src/pages/ExploreDrinks.jsx
src/pages/ExploreDrinksIngredients.jsx
src/pages/ExploreFoods.jsx
src/pages/ExploreFoodsArea.jsx
src/pages/ExploreFoodsIngredients.jsx
src/pages/FavoriteRecipes.jsx
src/pages/FoodDetails.jsx
src/pages/FoodInProgress.jsx
src/pages/Foods.jsx
src/pages/Profile.jsx
src/pages/RecipesDone.jsx
src/services/fetchAPI.js

Refatoração do provider e das dependências que ele fornece

Group 17 refatora codigo

---

src/App.css
src/components/BodyFavoriteRecipes.jsx
src/components/BodyRecipesDone.jsx
src/components/loopIngredientsAndMeasure.jsx
src/context/GlobalProvider.js
src/pages/DrinkDetails.jsx
src/pages/DrinkInProgress.jsx
src/pages/Drinks.jsx
src/pages/Explore.jsx
src/pages/ExploreDrinks.jsx
src/pages/ExploreFoods.jsx
src/pages/FavoriteRecipes.jsx
src/pages/FoodDetails.jsx
src/pages/FoodInProgress.jsx
src/pages/Foods.jsx

Group 17 refatora codigo / feat

---

src/App.css
src/components/BeveragesInProgressInfo.jsx
src/components/FoodInProgressInfo.jsx
src/components/Footer.jsx
src/components/Header.jsx
src/components/Recommendations.jsx
src/components/SearchBar.jsx
src/pages/BeverageIngredients.js
src/pages/BeverageRecipe.js
src/pages/Beverages.js
src/pages/DoneRecipes.js
src/pages/Explore.js
src/pages/ExploreBeverages.js
src/pages/ExploreFood.js
src/pages/FavoriteRecipes.js
src/pages/Food.js
src/pages/FoodByOrigin.js
src/pages/FoodIngredients.js
src/pages/FoodRecipe.js
src/pages/Profile.js

Feat: CSS da tela principal, incluindo os componentes SearchBar, Header e Footer.

[Group-31] CSS da Tela principal e componentes
